In [22]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation

data = np.loadtxt("trajectory.txt", converters = {1: lambda s: b"O" == s})
print(data)
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
times = np.unique(data[:,0])
def get_data(n):
    timeslice = data[data[:,0] == times[n]]
    is_oxygen = timeslice[:,1] == 1
    return timeslice[is_oxygen,2:], timeslice[~is_oxygen,2:]
data_0 = get_data(0)
oxygen_pts = ax.scatter(*data_0[0].T, c = 'b', marker='o')
hydrogen_pts = ax.scatter(*data_0[1].T, c = 'k', marker='o')

# don't show the plain background
plt.close()

# define function to draw each frame
def drawframe(n):
    if n % 10 == 1:
        print(f"Drawing frame {n} of {len(times)}")
    data_slice = get_data(n)
    oxygen_pts._offsets3d = data_slice[0].T
    hydrogen_pts._offsets3d = data_slice[1].T
    return oxygen_pts, hydrogen_pts

anim = animation.FuncAnimation(fig, drawframe, frames=len(times), interval=20, blit=True)

[[0.       1.       0.       0.       0.      ]
 [0.       1.       0.2      0.2      0.      ]
 [0.       1.       0.4      0.4      0.      ]
 ...
 [3.14617  0.       0.271146 0.284681 0.      ]
 [3.14617  0.       0.220232 0.512363 0.      ]
 [3.14617  0.       0.716003 0.598553 0.      ]]


In [23]:
anim.save("video.mp4")

Drawing frame 1 of 101
Drawing frame 11 of 101
Drawing frame 21 of 101
Drawing frame 31 of 101
Drawing frame 41 of 101
Drawing frame 51 of 101
Drawing frame 61 of 101
Drawing frame 71 of 101
Drawing frame 81 of 101
Drawing frame 91 of 101


In [24]:
from IPython.display import HTML
HTML(anim.to_html5_video())

Drawing frame 1 of 101
Drawing frame 11 of 101
Drawing frame 21 of 101
Drawing frame 31 of 101
Drawing frame 41 of 101
Drawing frame 51 of 101
Drawing frame 61 of 101
Drawing frame 71 of 101
Drawing frame 81 of 101
Drawing frame 91 of 101


In [25]:
times

array([0.00000e+00, 3.17763e-04, 3.20941e-02, 6.38704e-02, 9.56466e-02,
       1.27423e-01, 1.59199e-01, 1.90976e-01, 2.22752e-01, 2.54528e-01,
       2.86304e-01, 3.18081e-01, 3.49857e-01, 3.81633e-01, 4.13410e-01,
       4.45186e-01, 4.76962e-01, 5.08738e-01, 5.40515e-01, 5.72291e-01,
       6.04067e-01, 6.35844e-01, 6.67620e-01, 6.99396e-01, 7.31173e-01,
       7.62949e-01, 7.94725e-01, 8.26501e-01, 8.58278e-01, 8.90054e-01,
       9.21830e-01, 9.53607e-01, 9.85383e-01, 1.01716e+00, 1.04894e+00,
       1.08071e+00, 1.11249e+00, 1.14426e+00, 1.17604e+00, 1.20782e+00,
       1.23959e+00, 1.27137e+00, 1.30315e+00, 1.33492e+00, 1.36670e+00,
       1.39847e+00, 1.43025e+00, 1.46203e+00, 1.49380e+00, 1.52558e+00,
       1.55736e+00, 1.58913e+00, 1.62091e+00, 1.65269e+00, 1.68446e+00,
       1.71624e+00, 1.74801e+00, 1.77979e+00, 1.81157e+00, 1.84334e+00,
       1.87512e+00, 1.90690e+00, 1.93867e+00, 1.97045e+00, 2.00222e+00,
       2.03400e+00, 2.06578e+00, 2.09755e+00, 2.12933e+00, 2.161

In [26]:
get_data(1)

(array([[0. , 0. , 0. ],
        [0.2, 0.2, 0. ],
        [0.4, 0.4, 0. ],
        [0.6, 0.6, 0. ]]),
 array([[ 0.0757541,  0.058708 ,  0.       ],
        [ 0.275754 ,  0.258708 ,  0.       ],
        [ 0.475754 ,  0.458708 ,  0.       ],
        [ 0.675754 ,  0.658708 ,  0.       ],
        [-0.0757541,  0.058708 ,  0.       ],
        [ 0.124246 ,  0.258708 ,  0.       ],
        [ 0.324246 ,  0.458708 ,  0.       ],
        [ 0.524246 ,  0.658708 ,  0.       ]]))